### ISSUE TITLE
Rename this repo to deltachat-login-demo

### ISSUE THREAD

**Issue by pabzm** [deltachat/login-demo#4]
All deltachat-related repositories have a name starting with 'deltachat-'. I think we should adhere to that convention.

Any objections?

**Comment by hpk42** [comment]
On Wed, Dec 04, 2019 at 01:42 -0800, Pablo wrote:
> All deltachat-related repositories have a name starting with 'deltachat-'. I think we should adhere to that convention.
> 
> Any objections?

i'd rather rename the few which do have the unneccessary deltachat prefix :) 

i think the original reason from @r10s was that he wants to have

    "git checkout ..." 

to create a nice basename. But 

    "git checkout ... nice-basename" 

is not so hard.  In my case i have a "delta" dir where i put all checkouts
from the deltachat org so do the latter command already for some repos.

**Comment by r10s** [comment]
it's also about forking on github - sth. as `username/ios` say nothing. unfortunately, github does not allow to change the name during forking.

but maybe this is more a github issue that we can ignore. i would not be against leaving out `deltachat-` from the names, ~~however, maybe not do it just now as this is also some work to get rid of warnings in submodules etc.~~ EDIT: otoh, there would be some noise at any time. so, if we decide to rename, well, then just do it :)

wrt this repo: yip, just leave the name as it is and close this issue :)

**Comment by Simon-Laux** [comment]
I would also leave it like it is right now, because its a demo, not an super official program

**Comment by pabzm** [comment]
Now that it's linked from the forum I'd consider it at least semi-official. But anyway, if this change is controversial let's not spend more energy on it.
